### PR TITLE
add --require-selection option

### PR DESCRIPTION
**Pull request by bencollerson**
If true, return an error if no selection is made.

### CODE REVIEW

**Comment by bencollerson** [comment]
The idea behind this option is that it simplifies the process of evaluating whether the output from tofi should be ignored or not. Rather than looking for an empty string you can just check the return code.

**Comment by philj56** [comment]
Hey, sorry for the delay, and thanks for this! To be honest, I think this should just be the default, but it's a potentially breaking change so I'd normally go through the cycle of
  - Option (False by default) & warn in the release.
  - Option (True by default) & warn when using it.
  - Deprecate the option & remove in the future.

However, I doubt anyone is using tofi in a script like `tofi && something-else` currently (as it's pointless), and this is the way dmenu works, so I guess just going straight to to returning error on no selection is fine?

**Comment by bencollerson** [comment]
I agree this behaviour should be the default. And yeah I wrote this patch so it could be used for the first step in the sort of release plan you outline there. But if you think this change can be done without all the walking on eggshells, I could update the patch to just be "return error on no selection".

**Comment by bencollerson** [comment]
Replacing with this pull request: https://github.com/philj56/tofi/pull/111

**Pull request closed without merging**
